apiVersion: v1
kind: Namespace
metadata:
  name: NEIMAN
  labels:
    name: NEIMAN
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: NEIMAN-monitoring
  labels:
    name: NEIMAN-monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: NEIMAN-database
  labels:
    name: NEIMAN-database