apiVersion: v1
kind: ServiceAccount
metadata:
  name: NEIMAN-api
  namespace: NEIMAN
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: NEIMAN-web
  namespace: NEIMAN
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: NEIMAN-api-role
  namespace: NEIMAN
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: NEIMAN-api-rolebinding
  namespace: NEIMAN
subjects:
  - kind: ServiceAccount
    name: NEIMAN-api
    namespace: NEIMAN
roleRef:
  kind: Role
  name: NEIMAN-api-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: NEIMAN-web-role
  namespace: NEIMAN
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: NEIMAN-web-rolebinding
  namespace: NEIMAN
subjects:
  - kind: ServiceAccount
    name: NEIMAN-web
    namespace: NEIMAN
roleRef:
  kind: Role
  name: NEIMAN-web-role
  apiGroup: rbac.authorization.k8s.io